import { PIDGraph } from "@/types/workbench"

export const pidDiagramsList: PIDGraph[] = [
  {
    drawingId: "DWG-C101-ADU",
    drawingTitle: "Atmospheric Crude Distillation Unit (Column C-101)",
    standard: "ISA-5.1 / ASME Sec VIII",
    category: "Primary Separation",
    description: "Atmospheric crude fractionation tower with desalted crude preheat train, overhead condensing loop, and bottom reboiler circulation.",
    overlayImageUrl: "/PnID.png",
    flowNarrative: "1. Desalted crude oil enters from Feed Surge Drum V-102 at 280°C.\n2. Main Feed Booster Pump P-101A/B discharges through Pressure Transmitter PT-301 and Flow Control Valve FCV-101.\n3. Crude enters the flash zone of Distillation Column C-101 (36 fractionating trays).\n4. Overhead vapors (light naphtha & LPG) exit column top at 115°C into Overhead Condenser E-101.\n5. Condensed naphtha collects in Reflux Drum V-103; Reflux Pump P-102 returns light liquid via FCV-102 to maintain top tray temperature.\n6. Atmospheric residue drains from column bottom to vacuum unit transfer line.",
    equipmentCount: {
      valves: 4,
      pumps: 3,
      vessels: 3,
      instruments: 4,
    },
    nodes: [
      {
        id: "node-c101-v102",
        tag: "V-102",
        symbolType: "storage_tank",
        label: "Crude Surge Drum",
        bbox: [6, 38, 12, 24],
        confidence: 0.98,
        lineAssociation: "14\"-CRD-1001-A1A",
        status: "nominal",
        description: "Horizontal buffer drum providing 15-minute holdup volume upstream of distillation charge pump.",
      },
      {
        id: "node-c101-p101a",
        tag: "P-101A",
        symbolType: "centrifugal_pump",
        label: "Crude Charge Pump A",
        bbox: [22, 54, 9, 14],
        confidence: 0.96,
        lineAssociation: "10\"-CRD-1002-A1A",
        status: "nominal",
        description: "Electric motor driven multistage centrifugal pump, 450 m³/h capacity @ 18 bar discharge pressure.",
      },
      {
        id: "node-c101-pt301",
        tag: "PT-301",
        symbolType: "pressure_transmitter",
        label: "Discharge Pressure Transmitter",
        bbox: [34, 42, 7, 10],
        confidence: 0.94,
        lineAssociation: "Instrument Loop 301",
        status: "nominal",
        description: "Smart HART pressure transmitter with high-pressure safety interlock trip logic.",
      },
      {
        id: "node-c101-fcv101",
        tag: "FCV-101",
        symbolType: "control_valve",
        label: "Column Charge Control Valve",
        bbox: [44, 55, 8, 11],
        confidence: 0.95,
        lineAssociation: "10\"-CRD-1003-A1A",
        status: "nominal",
        description: "Pneumatic globe control valve with fail-closed (FC) actuator and smart positioner.",
      },
      {
        id: "node-c101-c101",
        tag: "C-101",
        symbolType: "distillation_column",
        label: "Atmospheric Distillation Column",
        bbox: [56, 14, 16, 68],
        confidence: 0.99,
        lineAssociation: "Main Fractionation Column",
        status: "nominal",
        description: "4.2m diameter x 48m tangent-to-tangent height column with 36 dual-flow valve trays.",
      },
      {
        id: "node-c101-e101",
        tag: "E-101",
        symbolType: "heat_exchanger",
        label: "Overhead Condenser",
        bbox: [76, 12, 11, 14],
        confidence: 0.93,
        lineAssociation: "20\"-VAP-1004-A1A",
        status: "nominal",
        description: "Shell and tube heat exchanger cooling overhead hydrocarbon vapors against cooling water.",
      },
      {
        id: "node-c101-v103",
        tag: "V-103",
        symbolType: "accumulator",
        label: "Overhead Reflux Drum",
        bbox: [82, 32, 11, 18],
        confidence: 0.94,
        lineAssociation: "12\"-NPH-1005-A1A",
        status: "nominal",
        description: "Horizontal three-phase separator with boot for condensed water drainage and naphtha collection.",
      },
      {
        id: "node-c101-p102",
        tag: "P-102",
        symbolType: "centrifugal_pump",
        label: "Reflux Return Pump",
        bbox: [78, 64, 8, 12],
        confidence: 0.91,
        lineAssociation: "6\"-RFL-1006-A1A",
        status: "nominal",
        description: "Canned motor pump circulating reflux to Tray 1 to maintain overhead distillation purity.",
      },
      {
        id: "node-c101-fcv102",
        tag: "FCV-102",
        symbolType: "control_valve",
        label: "Reflux Flow Control Valve",
        bbox: [68, 72, 7, 10],
        confidence: 0.90,
        lineAssociation: "6\"-RFL-1007-A1A",
        status: "nominal",
        description: "Equal percentage pneumatic valve actuated by column overhead temperature controller TIC-102.",
      },
    ],
    edges: [
      { id: "e1", fromNodeId: "node-c101-v102", toNodeId: "node-c101-p101a", lineType: "process_pipe", lineTag: "14\"-CRD-1001-A1A", flowDirection: "forward", confidence: 0.98 },
      { id: "e2", fromNodeId: "node-c101-p101a", toNodeId: "node-c101-pt301", lineType: "instrument_line", lineTag: "Signal Loop", flowDirection: "forward", confidence: 0.93 },
      { id: "e3", fromNodeId: "node-c101-p101a", toNodeId: "node-c101-fcv101", lineType: "process_pipe", lineTag: "10\"-CRD-1002-A1A", flowDirection: "forward", confidence: 0.97 },
      { id: "e4", fromNodeId: "node-c101-fcv101", toNodeId: "node-c101-c101", lineType: "process_pipe", lineTag: "10\"-CRD-1003-A1A", flowDirection: "forward", confidence: 0.98 },
      { id: "e5", fromNodeId: "node-c101-c101", toNodeId: "node-c101-e101", lineType: "process_pipe", lineTag: "20\"-VAP-1004-A1A", flowDirection: "forward", confidence: 0.95 },
      { id: "e6", fromNodeId: "node-c101-e101", toNodeId: "node-c101-v103", lineType: "process_pipe", lineTag: "12\"-NPH-1005-A1A", flowDirection: "forward", confidence: 0.94 },
      { id: "e7", fromNodeId: "node-c101-v103", toNodeId: "node-c101-p102", lineType: "process_pipe", lineTag: "8\"-RFL-1006-A1A", flowDirection: "forward", confidence: 0.92 },
      { id: "e8", fromNodeId: "node-c101-p102", toNodeId: "node-c101-fcv102", lineType: "process_pipe", lineTag: "6\"-RFL-1007-A1A", flowDirection: "forward", confidence: 0.93 },
      { id: "e9", fromNodeId: "node-c101-fcv102", toNodeId: "node-c101-c101", lineType: "process_pipe", lineTag: "6\"-RFL-1008-A1A", flowDirection: "forward", confidence: 0.94 },
    ],
  },
  {
    drawingId: "DWG-HDS-201",
    drawingTitle: "Diesel Hydrodesulfurization (DHDS) Reactor Loop",
    standard: "ISA-5.1 / API 537",
    category: "Hydroprocessing",
    description: "Catalytic hydrotreating loop for sulfur and nitrogen removal from gas oil using high pressure hydrogen over CoMo catalyst bed.",
    overlayImageUrl: "/PnID.png",
    flowNarrative: "1. Straight-run diesel blends with high-pressure Recycle Hydrogen from Compressor K-201 at 65 bar.\n2. Combined feed preheats through Feed/Effluent Exchanger E-201 and Fired Heater Furnace H-201 to 345°C.\n3. Stream enters Trickle Bed Reactor R-201 packed with Cobalt-Molybdenum desulfurization catalyst.\n4. Reactor effluent cools down through High Pressure Separator V-201 where sour recycle gas is separated from sweet diesel liquid.\n5. Overpressure safety loop is monitored by High-Integrity Pressure Protection System (HIPPS) and Depressuring Valve BDV-201.",
    equipmentCount: {
      valves: 5,
      pumps: 2,
      vessels: 3,
      instruments: 6,
    },
    nodes: [
      {
        id: "node-hds-h201",
        tag: "H-201",
        symbolType: "furnace",
        label: "HDS Charge Heater Furnace",
        bbox: [8, 30, 13, 32],
        confidence: 0.97,
        lineAssociation: "8\"-DSL-2001-C1A",
        status: "nominal",
        description: "Natural gas fired cabin heater with multi-pass radiant coils bringing feed to reaction temperature (345°C).",
      },
      {
        id: "node-hds-r201",
        tag: "R-201",
        symbolType: "reactor",
        label: "Hydrotreating Fixed-Bed Reactor",
        bbox: [28, 16, 16, 62],
        confidence: 0.99,
        lineAssociation: "8\"-RXF-2002-C1A",
        status: "nominal",
        description: "Thick-walled 2.25Cr-1Mo forged shell reactor with internal quench decks for bed temperature management.",
      },
      {
        id: "node-hds-bdv201",
        tag: "BDV-201",
        symbolType: "control_valve",
        label: "Emergency Depressuring Valve",
        bbox: [32, 4, 8, 10],
        confidence: 0.95,
        lineAssociation: "6\"-FLR-2003-C1A",
        status: "nominal",
        description: "SIL-3 rated emergency blowdown valve routing reactor inventory to high-pressure flare header during runaway.",
      },
      {
        id: "node-hds-e201",
        tag: "E-201",
        symbolType: "heat_exchanger",
        label: "Combined Feed / Effluent Exchanger",
        bbox: [50, 36, 12, 16],
        confidence: 0.96,
        lineAssociation: "10\"-RXE-2004-C1A",
        status: "nominal",
        description: "BEM-type shell & tube heat recovery exchanger transferring 14 MW thermal energy from reactor effluent to raw feed.",
      },
      {
        id: "node-hds-v201",
        tag: "V-201",
        symbolType: "knockout_drum",
        label: "High Pressure Separator (HPS)",
        bbox: [68, 26, 13, 34],
        confidence: 0.98,
        lineAssociation: "10\"-EFF-2005-C1A",
        status: "nominal",
        description: "Heavy wall vertical separator operating at 60 bar to separate hydrogen gas from desulfurized hydrocarbon liquid.",
      },
      {
        id: "node-hds-k201",
        tag: "K-201",
        symbolType: "compressor",
        label: "Recycle Hydrogen Compressor",
        bbox: [84, 18, 11, 15],
        confidence: 0.94,
        lineAssociation: "8\"-HYD-2006-C1A",
        status: "nominal",
        description: "Centrifugal barrel compressor driven by condensing steam turbine maintaining 65 bar hydrogen loop circulation.",
      },
    ],
    edges: [
      { id: "h1", fromNodeId: "node-hds-h201", toNodeId: "node-hds-r201", lineType: "process_pipe", lineTag: "8\"-RXF-2002-C1A", flowDirection: "forward", confidence: 0.98 },
      { id: "h2", fromNodeId: "node-hds-r201", toNodeId: "node-hds-bdv201", lineType: "process_pipe", lineTag: "6\"-FLR-2003-C1A", flowDirection: "forward", confidence: 0.94 },
      { id: "h3", fromNodeId: "node-hds-r201", toNodeId: "node-hds-e201", lineType: "process_pipe", lineTag: "10\"-RXE-2004-C1A", flowDirection: "forward", confidence: 0.97 },
      { id: "h4", fromNodeId: "node-hds-e201", toNodeId: "node-hds-v201", lineType: "process_pipe", lineTag: "10\"-EFF-2005-C1A", flowDirection: "forward", confidence: 0.96 },
      { id: "h5", fromNodeId: "node-hds-v201", toNodeId: "node-hds-k201", lineType: "process_pipe", lineTag: "8\"-HYD-2006-C1A", flowDirection: "forward", confidence: 0.95 },
      { id: "h6", fromNodeId: "node-hds-k201", toNodeId: "node-hds-h201", lineType: "process_pipe", lineTag: "8\"-HYD-2007-C1A", flowDirection: "forward", confidence: 0.93 },
    ],
  },
  {
    drawingId: "DWG-OVHD-105",
    drawingTitle: "Crude Overhead Condenser & Naphtha Stabilizer",
    standard: "ISA-5.1 / API 650",
    category: "Overhead System",
    description: "Overhead condensing and sour water separation system with automated acid gas neutralization and dual-reflux pumps.",
    overlayImageUrl: "/PnID.png",
    flowNarrative: "1. Overhead vapor leaves fractionator at 115°C through 24-inch header.\n2. Corrosion inhibitor and neutralizing amine injection prevents ammonium chloride deposition.\n3. Air-cooled fin-fan bank E-105A-D condenses hydro-carbons into two-phase liquid.\n4. Accumulator Drum V-103 separates light gas, sour water boot, and unstabilized naphtha.\n5. Split-range controller PCV-105 maintains column top pressure at 1.8 bar gauge.",
    equipmentCount: {
      valves: 4,
      pumps: 2,
      vessels: 2,
      instruments: 5,
    },
    nodes: [
      {
        id: "node-ovhd-e105",
        tag: "E-105A/B",
        symbolType: "heat_exchanger",
        label: "Fin-Fan Overhead Air Coolers",
        bbox: [10, 20, 18, 22],
        confidence: 0.96,
        lineAssociation: "24\"-OVH-1051-A1A",
        status: "nominal",
        description: "Four-bay induced draft air cooler with variable frequency drive fans for condensation control.",
      },
      {
        id: "node-ovhd-v103",
        tag: "V-103",
        symbolType: "accumulator",
        label: "Overhead Receiver / Boot Drum",
        bbox: [38, 28, 16, 28],
        confidence: 0.98,
        lineAssociation: "16\"-NPH-1052-A1A",
        status: "nominal",
        description: "Horizontal settling drum with level transmitters LT-103A/B controlling sour water drain valve LCV-103.",
      },
      {
        id: "node-ovhd-pcv105",
        tag: "PCV-105",
        symbolType: "control_valve",
        label: "Off-Gas Pressure Control Valve",
        bbox: [42, 10, 8, 10],
        confidence: 0.95,
        lineAssociation: "6\"-GAS-1053-A1A",
        status: "nominal",
        description: "Fast-acting globe valve maintaining constant column backpressure by venting offgas to fuel gas system.",
      },
      {
        id: "node-ovhd-p103a",
        tag: "P-103A",
        symbolType: "centrifugal_pump",
        label: "Naphtha Reflux Pump A",
        bbox: [64, 52, 10, 15],
        confidence: 0.94,
        lineAssociation: "8\"-NPH-1054-A1A",
        status: "nominal",
        description: "API 610 compliant overhung process pump delivering naphtha reflux back to column top tray.",
      },
      {
        id: "node-ovhd-p103b",
        tag: "P-103B",
        symbolType: "centrifugal_pump",
        label: "Naphtha Product Forwarding Pump B",
        bbox: [80, 52, 10, 15],
        confidence: 0.93,
        lineAssociation: "6\"-NPH-1055-A1A",
        status: "nominal",
        description: "Dedicated transfer pump forwarding unstabilized naphtha to the Continuous Catalytic Reformer (CCR).",
      },
    ],
    edges: [
      { id: "o1", fromNodeId: "node-ovhd-e105", toNodeId: "node-ovhd-v103", lineType: "process_pipe", lineTag: "16\"-NPH-1052-A1A", flowDirection: "forward", confidence: 0.97 },
      { id: "o2", fromNodeId: "node-ovhd-v103", toNodeId: "node-ovhd-pcv105", lineType: "process_pipe", lineTag: "6\"-GAS-1053-A1A", flowDirection: "forward", confidence: 0.95 },
      { id: "o3", fromNodeId: "node-ovhd-v103", toNodeId: "node-ovhd-p103a", lineType: "process_pipe", lineTag: "8\"-NPH-1054-A1A", flowDirection: "forward", confidence: 0.94 },
      { id: "o4", fromNodeId: "node-ovhd-v103", toNodeId: "node-ovhd-p103b", lineType: "process_pipe", lineTag: "6\"-NPH-1055-A1A", flowDirection: "forward", confidence: 0.93 },
    ],
  },
  {
    drawingId: "DWG-ISA-SYM",
    drawingTitle: "ISA-5.1 Standard Equipment & Symbology Reference Sheet",
    standard: "ANSI/ISA-5.1-2009 / ISO 10628",
    category: "Engineering Standards",
    description: "Complete equipment symbology taxonomy indexed directly from the plant standard blueprint (PnID.png). Click any symbol below to view its ISA identification rules.",
    overlayImageUrl: "/PnID.png",
    flowNarrative: "This standard index maps every vessel, column, tank, boiler, and specialty container recognized by the automated agent vision pipeline.\n\n• Column Taxonomy: Vertical Vessel, Mixing Vessel, Tray Column, Fluidized Bed, Staggered Baffle, Packing Column.\n• Storage Taxonomy: Cone Roof, Floating Roof, Dome Roof, Double Wall, Onion Tank.\n• Heat Transfer: Boilers, Dome Boilers, Heating-Cooling Jacket Vessels, Heat Exchangers.\n• Tag Rules: 1st Letter = Measured Variable (P/T/F/L), 2nd Letter = Function (I/C/T/V).",
    equipmentCount: {
      valves: 8,
      pumps: 6,
      vessels: 18,
      instruments: 12,
    },
    nodes: [
      {
        id: "sym-vert-vessel",
        tag: "V-VESSEL",
        symbolType: "vessel",
        label: "Vertical Vessel",
        bbox: [3, 2, 14, 11],
        confidence: 0.99,
        lineAssociation: "Section 1: Columns & Vessels",
        status: "nominal",
        description: "Standard vertical pressure vessel used for flash drums, surge vessels, and gas-liquid knockouts.",
      },
      {
        id: "sym-mixing-vessel",
        tag: "M-VESSEL",
        symbolType: "vessel",
        label: "Mixing Vessel with Agitator",
        bbox: [3, 14, 14, 12],
        confidence: 0.99,
        lineAssociation: "Section 1: Columns & Vessels",
        status: "nominal",
        description: "Vessel equipped with mechanical impeller/agitator for chemical blending, neutralization, or catalyst slurry suspension.",
      },
      {
        id: "sym-column",
        tag: "COL-STD",
        symbolType: "distillation_column",
        label: "Standard Process Column",
        bbox: [3, 28, 14, 12],
        confidence: 0.99,
        lineAssociation: "Section 1: Columns & Vessels",
        status: "nominal",
        description: "Continuous fractionation or absorption column with standardized top and bottom tangent lines.",
      },
      {
        id: "sym-tray-col",
        tag: "COL-TRAY",
        symbolType: "distillation_column",
        label: "Tray Fractionation Column",
        bbox: [3, 42, 14, 12],
        confidence: 0.99,
        lineAssociation: "Section 1: Columns & Vessels",
        status: "nominal",
        description: "Column fitted with sieve, valve, or bubble-cap trays for discrete vapor-liquid stage equilibrium separation.",
      },
      {
        id: "sym-fluidized-bed",
        tag: "COL-FLUID",
        symbolType: "reactor",
        label: "Fluidized Bed Column",
        bbox: [3, 56, 14, 12],
        confidence: 0.99,
        lineAssociation: "Section 1: Columns & Vessels",
        status: "nominal",
        description: "Upward gas flow suspending solid catalyst particles for high-rate catalytic reactions (e.g. FCC regenerate).",
      },
      {
        id: "sym-packing-col",
        tag: "COL-PACK",
        symbolType: "distillation_column",
        label: "Structured Packing Column",
        bbox: [22, 2, 14, 14],
        confidence: 0.99,
        lineAssociation: "Section 2: Packed Columns & Drums",
        status: "nominal",
        description: "Column with random or structured packing providing low pressure drop for vacuum distillation and gas sweetening.",
      },
      {
        id: "sym-drum",
        tag: "DRUM-HORIZ",
        symbolType: "knockout_drum",
        label: "Horizontal Process Drum",
        bbox: [22, 18, 14, 10],
        confidence: 0.99,
        lineAssociation: "Section 2: Packed Columns & Drums",
        status: "nominal",
        description: "Horizontal cylindrical vessel with dished heads for multi-phase settling and liquid accumulation.",
      },
      {
        id: "sym-ko-drum",
        tag: "KO-DRUM",
        symbolType: "knockout_drum",
        label: "Knock-Out Drum with Mist Eliminator",
        bbox: [22, 29, 14, 13],
        confidence: 0.99,
        lineAssociation: "Section 2: Packed Columns & Drums",
        status: "nominal",
        description: "Vertical drum with internal mesh wire demister pad to remove entrained liquid droplets from vapor streams.",
      },
      {
        id: "sym-boiler",
        tag: "BLR-STD",
        symbolType: "furnace",
        label: "Standard Industrial Boiler",
        bbox: [41, 2, 14, 12],
        confidence: 0.99,
        lineAssociation: "Section 3: Boilers & Tanks",
        status: "nominal",
        description: "Steam generator converting boiler feedwater to high-pressure utility steam (HP/MP steam).",
      },
      {
        id: "sym-dome-boiler",
        tag: "BLR-DOME",
        symbolType: "furnace",
        label: "Dome Steam Boiler",
        bbox: [41, 14, 14, 12],
        confidence: 0.99,
        lineAssociation: "Section 3: Boilers & Tanks",
        status: "nominal",
        description: "Boiler with integrated steam dome reservoir for moisture-free saturated or superheated steam withdrawal.",
      },
      {
        id: "sym-cone-tank",
        tag: "TK-CONE",
        symbolType: "storage_tank",
        label: "Cone Roof Storage Tank",
        bbox: [60, 50, 14, 12],
        confidence: 0.99,
        lineAssociation: "Section 4: Atmospheric Storage",
        status: "nominal",
        description: "API 650 fixed-roof storage tank for non-volatile liquid petroleum products (heavy fuel oil, diesel).",
      },
      {
        id: "sym-float-roof",
        tag: "TK-FLOAT",
        symbolType: "storage_tank",
        label: "Floating Roof Tank (External)",
        bbox: [60, 14, 14, 12],
        confidence: 0.99,
        lineAssociation: "Section 4: Atmospheric Storage",
        status: "nominal",
        description: "Tank roof that rises and falls with liquid level, eliminating vapor space to minimize hydrocarbon VOC emissions.",
      },
      {
        id: "sym-jacket-vessel",
        tag: "VES-JACKET",
        symbolType: "heat_exchanger",
        label: "Heating/Cooling Jacket Vessel",
        bbox: [79, 14, 14, 12],
        confidence: 0.99,
        lineAssociation: "Section 5: Specialty Thermal Vessels",
        status: "nominal",
        description: "Vessel surrounded by an annular thermal fluid jacket for precise process temperature maintenance.",
      },
      {
        id: "sym-double-wall",
        tag: "TK-DBL-WALL",
        symbolType: "storage_tank",
        label: "Double Wall Cryogenic / Chemical Tank",
        bbox: [60, 75, 14, 12],
        confidence: 0.99,
        lineAssociation: "Section 4: Atmospheric Storage",
        status: "nominal",
        description: "Dual-containment tank for hazardous chemicals and refrigerated LPG storage with interstitial leak detection.",
      },
    ],
    edges: [],
  },
]
